// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentManagementSystem.Model;

namespace StudentManagementSystem.Migrations
{
    [DbContext(typeof(StudentManagementDb))]
    [Migration("20200128194953_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("StudentManagementSystem.Model.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Admin");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.Model.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CityOfResidence")
                        .HasColumnType("TEXT");

                    b.Property<int>("Department")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Student");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityOfResidence = "Dhaka",
                            Department = 0,
                            FirstName = "Hossain",
                            LastName = "Tanvir",
                            StudentId = "123451"
                        },
                        new
                        {
                            Id = 2,
                            CityOfResidence = "Dhaka",
                            Department = 1,
                            FirstName = "Ali",
                            LastName = "Mohammad",
                            StudentId = "123452"
                        },
                        new
                        {
                            Id = 3,
                            CityOfResidence = "Dhaka",
                            Department = 3,
                            FirstName = "Ahamed",
                            LastName = "Foysal",
                            StudentId = "123453"
                        },
                        new
                        {
                            Id = 4,
                            CityOfResidence = "Dhaka",
                            Department = 2,
                            FirstName = "Miah",
                            LastName = "Tuhin",
                            StudentId = "123454"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
